export type WoolworthsProduct = {
  id: string
  name: string
  category: string
  brand: string
  servingSize: number // grams
  servingSizeUnit: string
  calories: number // per serving
  protein: number // grams per serving
  fat: number // grams per serving
  carbs: number // grams per serving
  fiber: number // grams per serving
  sugar: number // grams per serving
}

export const woolworthsProducts: WoolworthsProduct[] = [
  // Proteins
  {
    id: "wool-chicken-breast",
    name: "Chicken Breast Fillet",
    category: "Poultry",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-beef-steak",
    name: "Beef Steak (Sirloin)",
    category: "Beef",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 250,
    protein: 26,
    fat: 15,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-salmon-fillet",
    name: "Salmon Fillet",
    category: "Seafood",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 206,
    protein: 22,
    fat: 13,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-egg",
    name: "Eggs (Large)",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 50,
    servingSizeUnit: "g",
    calories: 78,
    protein: 6.3,
    fat: 5.3,
    carbs: 0.6,
    fiber: 0,
    sugar: 0.4,
  },
  {
    id: "wool-greek-yogurt",
    name: "Greek Yogurt (Plain)",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 59,
    protein: 10,
    fat: 0.5,
    carbs: 3.3,
    fiber: 0,
    sugar: 2.7,
  },
  // Carbs
  {
    id: "wool-rice-white",
    name: "White Rice (Cooked)",
    category: "Grains",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 130,
    protein: 2.7,
    fat: 0.3,
    carbs: 28,
    fiber: 0.4,
    sugar: 0.1,
  },
  {
    id: "wool-oats",
    name: "Oats (Dry)",
    category: "Grains",
    brand: "Woolworths",
    servingSize: 40,
    servingSizeUnit: "g",
    calories: 150,
    protein: 5,
    fat: 3,
    carbs: 27,
    fiber: 4,
    sugar: 1,
  },
  {
    id: "wool-bread-wholemeal",
    name: "Wholemeal Bread (Slice)",
    category: "Bread",
    brand: "Woolworths",
    servingSize: 30,
    servingSizeUnit: "g",
    calories: 80,
    protein: 3.6,
    fat: 1.2,
    carbs: 14,
    fiber: 2.4,
    sugar: 1.5,
  },
  {
    id: "wool-sweet-potato",
    name: "Sweet Potato (Cooked)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20,
    fiber: 3,
    sugar: 4.2,
  },
  {
    id: "wool-banana",
    name: "Banana (Medium)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 118,
    servingSizeUnit: "g",
    calories: 105,
    protein: 1.3,
    fat: 0.3,
    carbs: 27,
    fiber: 3.1,
    sugar: 14,
  },
  // Vegetables
  {
    id: "wool-broccoli",
    name: "Broccoli (Cooked)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 7,
    fiber: 2.4,
    sugar: 1.4,
  },
  {
    id: "wool-spinach",
    name: "Spinach (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 30,
    servingSizeUnit: "g",
    calories: 8,
    protein: 0.9,
    fat: 0.1,
    carbs: 1.4,
    fiber: 0.7,
    sugar: 0.04,
  },
  {
    id: "wool-carrot",
    name: "Carrot (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 61,
    servingSizeUnit: "g",
    calories: 26,
    protein: 0.6,
    fat: 0.1,
    carbs: 6.1,
    fiber: 1.7,
    sugar: 3,
  },
  // Fats & Nuts
  {
    id: "wool-almond-butter",
    name: "Almond Butter (2 tbsp)",
    category: "Nuts & Seeds",
    brand: "Woolworths",
    servingSize: 32,
    servingSizeUnit: "g",
    calories: 190,
    protein: 7,
    fat: 17,
    carbs: 7,
    fiber: 3.5,
    sugar: 1,
  },
  {
    id: "wool-olive-oil",
    name: "Olive Oil (1 tbsp)",
    category: "Oils",
    brand: "Woolworths",
    servingSize: 15,
    servingSizeUnit: "ml",
    calories: 120,
    protein: 0,
    fat: 14,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  // Dairy
  {
    id: "wool-milk-full",
    name: "Full Fat Milk",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 200,
    servingSizeUnit: "ml",
    calories: 130,
    protein: 6.6,
    fat: 7,
    carbs: 9.4,
    fiber: 0,
    sugar: 9.4,
  },
  {
    id: "wool-cheese-cheddar",
    name: "Cheddar Cheese",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 28,
    servingSizeUnit: "g",
    calories: 113,
    protein: 7,
    fat: 9.5,
    carbs: 0.4,
    fiber: 0,
    sugar: 0.1,
  },
  // Processed/Ready meals
  {
    id: "wool-protein-bar",
    name: "Protein Bar (Chocolate)",
    category: "Snacks",
    brand: "Woolworths",
    servingSize: 40,
    servingSizeUnit: "g",
    calories: 170,
    protein: 15,
    fat: 8,
    carbs: 12,
    fiber: 2,
    sugar: 3,
  },
  {
    id: "wool-chicken-breast-grilled",
    name: "Grilled Chicken Breast (Pre-cooked)",
    category: "Ready Meals",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 165,
    protein: 32,
    fat: 2,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-whey-protein",
    name: "Whey Protein Powder (Vanilla)",
    category: "Supplements",
    brand: "Woolworths",
    servingSize: 30,
    servingSizeUnit: "g",
    calories: 110,
    protein: 24,
    fat: 1,
    carbs: 2,
    fiber: 0,
    sugar: 0.5,
  },
  // Additional Proteins
  {
    id: "wool-ground-beef",
    name: "Ground Beef (93% Lean)",
    category: "Beef",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 182,
    protein: 24,
    fat: 9,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-turkey-breast",
    name: "Turkey Breast Fillet",
    category: "Poultry",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 135,
    protein: 30,
    fat: 0.5,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-pork-loin",
    name: "Pork Loin Chop",
    category: "Pork",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 242,
    protein: 27,
    fat: 14,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-tuna-canned",
    name: "Tuna in Water (Canned)",
    category: "Seafood",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 96,
    protein: 21,
    fat: 0.8,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-cod-fillet",
    name: "Cod Fillet",
    category: "Seafood",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 82,
    protein: 18,
    fat: 0.7,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-shrimp",
    name: "Shrimp (Raw)",
    category: "Seafood",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 99,
    protein: 24,
    fat: 0.3,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-cottage-cheese",
    name: "Cottage Cheese (Low Fat)",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 79,
    protein: 11,
    fat: 1.1,
    carbs: 3.4,
    fiber: 0,
    sugar: 3,
  },
  {
    id: "wool-tofu",
    name: "Tofu (Firm)",
    category: "Plant Protein",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 76,
    protein: 8,
    fat: 4.8,
    carbs: 1.9,
    fiber: 0,
    sugar: 0.2,
  },
  {
    id: "wool-chickpeas-canned",
    name: "Chickpeas (Canned)",
    category: "Legumes",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 134,
    protein: 8.9,
    fat: 2.1,
    carbs: 22,
    fiber: 5.9,
    sugar: 4,
  },
  {
    id: "wool-lentils-cooked",
    name: "Lentils (Cooked)",
    category: "Legumes",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 116,
    protein: 9,
    fat: 0.4,
    carbs: 20,
    fiber: 7.9,
    sugar: 1.6,
  },
  // Additional Carbs
  {
    id: "wool-brown-rice",
    name: "Brown Rice (Cooked)",
    category: "Grains",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 111,
    protein: 2.6,
    fat: 0.9,
    carbs: 23,
    fiber: 1.8,
    sugar: 0.3,
  },
  {
    id: "wool-quinoa-cooked",
    name: "Quinoa (Cooked)",
    category: "Grains",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 120,
    protein: 4.4,
    fat: 1.9,
    carbs: 21,
    fiber: 2.8,
    sugar: 1.6,
  },
  {
    id: "wool-pasta-whole-wheat",
    name: "Whole Wheat Pasta (Cooked)",
    category: "Pasta",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 124,
    protein: 3.7,
    fat: 1.1,
    carbs: 26,
    fiber: 4.7,
    sugar: 0.5,
  },
  {
    id: "wool-cereal-granola",
    name: "Granola (Low Sugar)",
    category: "Cereals",
    brand: "Woolworths",
    servingSize: 40,
    servingSizeUnit: "g",
    calories: 180,
    protein: 4,
    fat: 8,
    carbs: 24,
    fiber: 2.5,
    sugar: 4,
  },
  {
    id: "wool-white-bread",
    name: "White Bread (Slice)",
    category: "Bread",
    brand: "Woolworths",
    servingSize: 28,
    servingSizeUnit: "g",
    calories: 79,
    protein: 2.7,
    fat: 1,
    carbs: 14,
    fiber: 0.6,
    sugar: 2,
  },
  {
    id: "wool-rye-bread",
    name: "Rye Bread (Slice)",
    category: "Bread",
    brand: "Woolworths",
    servingSize: 32,
    servingSizeUnit: "g",
    calories: 83,
    protein: 2.7,
    fat: 1.1,
    carbs: 15,
    fiber: 1.9,
    sugar: 0.8,
  },
  {
    id: "wool-potato-boiled",
    name: "Potato (Boiled)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 77,
    protein: 2.1,
    fat: 0.1,
    carbs: 17,
    fiber: 2.1,
    sugar: 0.8,
  },
  {
    id: "wool-corn-cooked",
    name: "Corn (Boiled)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 96,
    protein: 3.3,
    fat: 1.5,
    carbs: 21,
    fiber: 2.4,
    sugar: 6.3,
  },
  // Additional Fruits
  {
    id: "wool-apple",
    name: "Apple (Medium)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 182,
    servingSizeUnit: "g",
    calories: 95,
    protein: 0.5,
    fat: 0.3,
    carbs: 25,
    fiber: 4.4,
    sugar: 19,
  },
  {
    id: "wool-orange",
    name: "Orange (Medium)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 154,
    servingSizeUnit: "g",
    calories: 73,
    protein: 1.5,
    fat: 0.2,
    carbs: 18,
    fiber: 2.9,
    sugar: 12,
  },
  {
    id: "wool-strawberry",
    name: "Strawberry (Raw)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 152,
    servingSizeUnit: "g",
    calories: 49,
    protein: 1,
    fat: 0.5,
    carbs: 12,
    fiber: 2.9,
    sugar: 7.4,
  },
  {
    id: "wool-blueberry",
    name: "Blueberry (Raw)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 148,
    servingSizeUnit: "g",
    calories: 84,
    protein: 1.1,
    fat: 0.3,
    carbs: 21,
    fiber: 3.6,
    sugar: 15,
  },
  {
    id: "wool-avocado",
    name: "Avocado (Half)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 68,
    servingSizeUnit: "g",
    calories: 121,
    protein: 1.5,
    fat: 11,
    carbs: 6,
    fiber: 4.8,
    sugar: 0.3,
  },
  // Additional Vegetables
  {
    id: "wool-bell-pepper",
    name: "Bell Pepper (Red, Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 149,
    servingSizeUnit: "g",
    calories: 37,
    protein: 1.2,
    fat: 0.3,
    carbs: 9,
    fiber: 2.7,
    sugar: 6,
  },
  {
    id: "wool-tomato",
    name: "Tomato (Medium, Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 123,
    servingSizeUnit: "g",
    calories: 22,
    protein: 1.1,
    fat: 0.2,
    carbs: 5,
    fiber: 1.5,
    sugar: 3,
  },
  {
    id: "wool-cucumber",
    name: "Cucumber (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 52,
    servingSizeUnit: "g",
    calories: 8,
    protein: 0.4,
    fat: 0.1,
    carbs: 2,
    fiber: 0.4,
    sugar: 0.9,
  },
  {
    id: "wool-broccoli-raw",
    name: "Broccoli (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 91,
    servingSizeUnit: "g",
    calories: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 7,
    fiber: 1.5,
    sugar: 1.4,
  },
  {
    id: "wool-cauliflower",
    name: "Cauliflower (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 107,
    servingSizeUnit: "g",
    calories: 25,
    protein: 2,
    fat: 0.3,
    carbs: 5,
    fiber: 2.4,
    sugar: 2,
  },
  {
    id: "wool-green-beans",
    name: "Green Beans (Cooked)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 31,
    protein: 1.9,
    fat: 0.2,
    carbs: 7,
    fiber: 2.7,
    sugar: 1.5,
  },
  {
    id: "wool-zucchini",
    name: "Zucchini (Cooked)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 124,
    servingSizeUnit: "g",
    calories: 21,
    protein: 1.4,
    fat: 0.4,
    carbs: 3.5,
    fiber: 0.6,
    sugar: 2.3,
  },
  // Nuts & Seeds
  {
    id: "wool-almonds",
    name: "Almonds (Roasted)",
    category: "Nuts & Seeds",
    brand: "Woolworths",
    servingSize: 28,
    servingSizeUnit: "g",
    calories: 164,
    protein: 6,
    fat: 14,
    carbs: 6,
    fiber: 3.5,
    sugar: 1.2,
  },
  {
    id: "wool-peanut-butter",
    name: "Peanut Butter (Natural)",
    category: "Nuts & Seeds",
    brand: "Woolworths",
    servingSize: 32,
    servingSizeUnit: "g",
    calories: 188,
    protein: 8,
    fat: 16,
    carbs: 7,
    fiber: 3,
    sugar: 1,
  },
  {
    id: "wool-cashews",
    name: "Cashews (Roasted)",
    category: "Nuts & Seeds",
    brand: "Woolworths",
    servingSize: 28,
    servingSizeUnit: "g",
    calories: 157,
    protein: 5,
    fat: 12,
    carbs: 9,
    fiber: 0.9,
    sugar: 1.7,
  },
  {
    id: "wool-chia-seeds",
    name: "Chia Seeds",
    category: "Nuts & Seeds",
    brand: "Woolworths",
    servingSize: 15,
    servingSizeUnit: "g",
    calories: 69,
    protein: 2.2,
    fat: 4.3,
    carbs: 6,
    fiber: 4.8,
    sugar: 0,
  },
  // Beverages
  {
    id: "wool-orange-juice",
    name: "Orange Juice (100% Fresh)",
    category: "Beverages",
    brand: "Woolworths",
    servingSize: 240,
    servingSizeUnit: "ml",
    calories: 110,
    protein: 2,
    fat: 0.5,
    carbs: 26,
    fiber: 0.5,
    sugar: 21,
  },
  {
    id: "wool-almond-milk",
    name: "Almond Milk (Unsweetened)",
    category: "Beverages",
    brand: "Woolworths",
    servingSize: 240,
    servingSizeUnit: "ml",
    calories: 30,
    protein: 1,
    fat: 2.5,
    carbs: 1,
    fiber: 0,
    sugar: 0,
  },
  // Condiments & Others
  {
    id: "wool-honey",
    name: "Honey (1 tbsp)",
    category: "Condiments",
    brand: "Woolworths",
    servingSize: 21,
    servingSizeUnit: "g",
    calories: 64,
    protein: 0.1,
    fat: 0,
    carbs: 17,
    fiber: 0,
    sugar: 16,
  },
  {
    id: "wool-peanut-butter-bar",
    name: "Peanut Butter Protein Bar",
    category: "Snacks",
    brand: "Woolworths",
    servingSize: 45,
    servingSizeUnit: "g",
    calories: 200,
    protein: 16,
    fat: 10,
    carbs: 14,
    fiber: 2,
    sugar: 2,
  },
  {
    id: "wool-greek-yogurt-berry",
    name: "Greek Yogurt with Berries",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 170,
    servingSizeUnit: "g",
    calories: 150,
    protein: 17,
    fat: 2,
    carbs: 12,
    fiber: 1,
    sugar: 8,
  },
  {
    id: "wool-granola-yogurt",
    name: "Granola with Yogurt Mix",
    category: "Snacks",
    brand: "Woolworths",
    servingSize: 200,
    servingSizeUnit: "g",
    calories: 280,
    protein: 12,
    fat: 10,
    carbs: 36,
    fiber: 3.5,
    sugar: 14,
  },
  {
    id: "wool-trail-mix",
    name: "Trail Mix (Nuts & Dried Fruit)",
    category: "Snacks",
    brand: "Woolworths",
    servingSize: 40,
    servingSizeUnit: "g",
    calories: 180,
    protein: 5,
    fat: 10,
    carbs: 18,
    fiber: 2.5,
    sugar: 10,
  },
]

export function searchWoolworthsProducts(query: string): WoolworthsProduct[] {
  const lowerQuery = query.toLowerCase()
  return woolworthsProducts.filter(
    (product) =>
      product.name.toLowerCase().includes(lowerQuery) ||
      product.category.toLowerCase().includes(lowerQuery) ||
      product.brand.toLowerCase().includes(lowerQuery),
  )
}

export function getProductById(id: string): WoolworthsProduct | undefined {
  return woolworthsProducts.find((product) => product.id === id)
}

export function calculateNutrients(product: WoolworthsProduct, grams: number) {
  const multiplier = grams / product.servingSize
  return {
    calories: Math.round(product.calories * multiplier),
    protein: Math.round(product.protein * multiplier * 10) / 10,
    fat: Math.round(product.fat * multiplier * 10) / 10,
    carbs: Math.round(product.carbs * multiplier * 10) / 10,
    fiber: Math.round(product.fiber * multiplier * 10) / 10,
    sugar: Math.round(product.sugar * multiplier * 10) / 10,
  }
}
