export type WoolworthsProduct = {
  id: string
  name: string
  category: string
  brand: string
  servingSize: number // grams
  servingSizeUnit: string
  calories: number // per serving
  protein: number // grams per serving
  fat: number // grams per serving
  carbs: number // grams per serving
  fiber: number // grams per serving
  sugar: number // grams per serving
}

export const woolworthsProducts: WoolworthsProduct[] = [
  // Proteins
  {
    id: "wool-chicken-breast",
    name: "Chicken Breast Fillet",
    category: "Poultry",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-beef-steak",
    name: "Beef Steak (Sirloin)",
    category: "Beef",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 250,
    protein: 26,
    fat: 15,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-salmon-fillet",
    name: "Salmon Fillet",
    category: "Seafood",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 206,
    protein: 22,
    fat: 13,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-egg",
    name: "Eggs (Large)",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 50,
    servingSizeUnit: "g",
    calories: 78,
    protein: 6.3,
    fat: 5.3,
    carbs: 0.6,
    fiber: 0,
    sugar: 0.4,
  },
  {
    id: "wool-greek-yogurt",
    name: "Greek Yogurt (Plain)",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 59,
    protein: 10,
    fat: 0.5,
    carbs: 3.3,
    fiber: 0,
    sugar: 2.7,
  },
  // Carbs
  {
    id: "wool-rice-white",
    name: "White Rice (Cooked)",
    category: "Grains",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 130,
    protein: 2.7,
    fat: 0.3,
    carbs: 28,
    fiber: 0.4,
    sugar: 0.1,
  },
  {
    id: "wool-oats",
    name: "Oats (Dry)",
    category: "Grains",
    brand: "Woolworths",
    servingSize: 40,
    servingSizeUnit: "g",
    calories: 150,
    protein: 5,
    fat: 3,
    carbs: 27,
    fiber: 4,
    sugar: 1,
  },
  {
    id: "wool-bread-wholemeal",
    name: "Wholemeal Bread (Slice)",
    category: "Bread",
    brand: "Woolworths",
    servingSize: 30,
    servingSizeUnit: "g",
    calories: 80,
    protein: 3.6,
    fat: 1.2,
    carbs: 14,
    fiber: 2.4,
    sugar: 1.5,
  },
  {
    id: "wool-sweet-potato",
    name: "Sweet Potato (Cooked)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20,
    fiber: 3,
    sugar: 4.2,
  },
  {
    id: "wool-banana",
    name: "Banana (Medium)",
    category: "Fruits",
    brand: "Woolworths",
    servingSize: 118,
    servingSizeUnit: "g",
    calories: 105,
    protein: 1.3,
    fat: 0.3,
    carbs: 27,
    fiber: 3.1,
    sugar: 14,
  },
  // Vegetables
  {
    id: "wool-broccoli",
    name: "Broccoli (Cooked)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 7,
    fiber: 2.4,
    sugar: 1.4,
  },
  {
    id: "wool-spinach",
    name: "Spinach (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 30,
    servingSizeUnit: "g",
    calories: 8,
    protein: 0.9,
    fat: 0.1,
    carbs: 1.4,
    fiber: 0.7,
    sugar: 0.04,
  },
  {
    id: "wool-carrot",
    name: "Carrot (Raw)",
    category: "Vegetables",
    brand: "Woolworths",
    servingSize: 61,
    servingSizeUnit: "g",
    calories: 26,
    protein: 0.6,
    fat: 0.1,
    carbs: 6.1,
    fiber: 1.7,
    sugar: 3,
  },
  // Fats & Nuts
  {
    id: "wool-almond-butter",
    name: "Almond Butter (2 tbsp)",
    category: "Nuts & Seeds",
    brand: "Woolworths",
    servingSize: 32,
    servingSizeUnit: "g",
    calories: 190,
    protein: 7,
    fat: 17,
    carbs: 7,
    fiber: 3.5,
    sugar: 1,
  },
  {
    id: "wool-olive-oil",
    name: "Olive Oil (1 tbsp)",
    category: "Oils",
    brand: "Woolworths",
    servingSize: 15,
    servingSizeUnit: "ml",
    calories: 120,
    protein: 0,
    fat: 14,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  // Dairy
  {
    id: "wool-milk-full",
    name: "Full Fat Milk",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 200,
    servingSizeUnit: "ml",
    calories: 130,
    protein: 6.6,
    fat: 7,
    carbs: 9.4,
    fiber: 0,
    sugar: 9.4,
  },
  {
    id: "wool-cheese-cheddar",
    name: "Cheddar Cheese",
    category: "Dairy",
    brand: "Woolworths",
    servingSize: 28,
    servingSizeUnit: "g",
    calories: 113,
    protein: 7,
    fat: 9.5,
    carbs: 0.4,
    fiber: 0,
    sugar: 0.1,
  },
  // Processed/Ready meals
  {
    id: "wool-protein-bar",
    name: "Protein Bar (Chocolate)",
    category: "Snacks",
    brand: "Woolworths",
    servingSize: 40,
    servingSizeUnit: "g",
    calories: 170,
    protein: 15,
    fat: 8,
    carbs: 12,
    fiber: 2,
    sugar: 3,
  },
  {
    id: "wool-chicken-breast-grilled",
    name: "Grilled Chicken Breast (Pre-cooked)",
    category: "Ready Meals",
    brand: "Woolworths",
    servingSize: 100,
    servingSizeUnit: "g",
    calories: 165,
    protein: 32,
    fat: 2,
    carbs: 0,
    fiber: 0,
    sugar: 0,
  },
  {
    id: "wool-whey-protein",
    name: "Whey Protein Powder (Vanilla)",
    category: "Supplements",
    brand: "Woolworths",
    servingSize: 30,
    servingSizeUnit: "g",
    calories: 110,
    protein: 24,
    fat: 1,
    carbs: 2,
    fiber: 0,
    sugar: 0.5,
  },
]

export function searchWoolworthsProducts(query: string): WoolworthsProduct[] {
  const lowerQuery = query.toLowerCase()
  return woolworthsProducts.filter(
    (product) =>
      product.name.toLowerCase().includes(lowerQuery) ||
      product.category.toLowerCase().includes(lowerQuery) ||
      product.brand.toLowerCase().includes(lowerQuery),
  )
}

export function getProductById(id: string): WoolworthsProduct | undefined {
  return woolworthsProducts.find((product) => product.id === id)
}

export function calculateNutrients(product: WoolworthsProduct, grams: number) {
  const multiplier = grams / product.servingSize
  return {
    calories: Math.round(product.calories * multiplier),
    protein: Math.round(product.protein * multiplier * 10) / 10,
    fat: Math.round(product.fat * multiplier * 10) / 10,
    carbs: Math.round(product.carbs * multiplier * 10) / 10,
    fiber: Math.round(product.fiber * multiplier * 10) / 10,
    sugar: Math.round(product.sugar * multiplier * 10) / 10,
  }
}
